version: '3.8'

services:
  openbooks:
    build: .
    container_name: openbooks-kindle
    ports:
      - "5228:80"
    volumes:
      - books_data:/books
      - ./logs:/app/logs
    environment:
      # Base configuration
      - BASE_PATH=/
      
      # SMTP Configuration for Send to Kindle
      - SMTP_ENABLED=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_app_password
      - SMTP_FROM=your_email@gmail.com
    command: ["./openbooks", "server", "--name", "", "--persist", "--no-browser-downloads", "--dir", "/books", "--port", "80"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  books_data:
    driver: local
