// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS-0]
	_ = x[CONNECT-1]
	_ = x[SEARCH-2]
	_ = x[DOWNLOAD-3]
	_ = x[SEND_TO_KINDLE-4]
	_ = x[RATELIMIT-5]
}

const _MessageType_name = "STATUSCONNECTSEARCHDOWNLOADSEND_TO_KINDLERATELIMIT"

var _MessageType_index = [...]uint8{0, 6, 13, 19, 27, 41, 50}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
